spring.application.name=ecommerce-cloud

#Configuracao com a base de dados mysql
spring.datasource.url=jdbc:mysql://localhost:3306/ibmec-cloud-mall
spring.datasource.username=root
spring.datasource.password=mysqlroot
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Azure CosmosDB Config
azure.cosmos.uri=https://ibmec-cloud-ecommerce.documents.azure.com:443/
azure.cosmos.key=N3CP3sW6Ys41hom4r3mzd9ZiiyetXU4Pn1sACdrzp68VSUQ76GN34TIxJEuhL6tB3sj2etBnqhlVACDbJyiK2Q==
azure.cosmos.database=ecommerce
azure.cosmos.query-metrics-enabled=true
azure.cosmos.response-diagnostics-enabled=false

